name: sina_mobile
description: "SINA mobile app"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: ^10.2.0
  fl_chart: ^0.66.1
  http: ^1.4.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  path_provider: ^2.1.2
  mime: ^1.0.4
  html: ^0.15.4
  intl: ^0.19.0
  image_picker: ^1.0.4
  permission_handler: ^11.0.0
  pie_chart: ^5.3.2
  lottie: ^3.3.1
  barcode_widget: ^2.0.1
  pdfx: ^2.4.0
  open_file: ^3.3.2
  url_launcher: ^6.1.11
  awesome_snackbar_content: ^0.1.3
  device_info_plus: ^9.0.0
  flutter_pdfview: ^1.2.5
  photo_view: ^0.14.0
  video_player: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "lib/asset/image/icon_sina.png"

flutter:
  uses-material-design: true

  assets:
    - lib/asset/image/
    - lib/asset/image/SINA.png
    - lib/asset/image/SINA v2.png
    - lib/asset/image/loginLogo.png
    - lib/asset/animation/success.lottie
    - lib/asset/Animation/success.json

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/asset/Font/Poppins-Regular.ttf
